[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Genome Browser FAQ"
authors = [{name = "Jairo", email = "jnavarr5@ucsc.edu"}]
dynamic = ["version", "description"]
